name: Add preview URL to PR description
on:
  pull_request_target:
    types: [opened]
    paths:
      - '**.md'
      - '**.png'
      - '**.rst'
      - '**.svg'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: edit-pull-request-description
        uses: Jerome1337/comment-pull-request@77a1932e3cac02d55e5b9ce108607aaea45663a8 # v1.0.4

        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          description-message: |
            
            Preview build: https://dash-docs-platform--${{github.event.pull_request.number}}.org.readthedocs.build/en/${{github.event.pull_request.number}}/
